//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOnConectorSIRE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOnConectorSIRE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP 1 &quot;Code&quot;, &quot;U_EXX_DATE&quot;, &quot;U_EXX_HORA&quot;, &quot;U_EXX_ARCHTXT&quot;, &quot;U_EXX_CONTENIDO&quot; FROM &quot;@EXX_SIRE_SERV&quot;
        ///WHERE &quot;U_EXX_TIPO&quot; = {0} AND &quot;U_EXX_BPLID&quot; = &apos;{1}&apos; AND &quot;U_EXX_PERIODO&quot; = &apos;{2}&apos; AND &quot;U_EXX_ESTADO&quot; = 0 ORDER BY &quot;Code&quot; DESC.
        /// </summary>
        internal static string HANA_ConsultaExisteLog {
            get {
                return ResourceManager.GetString("HANA_ConsultaExisteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM &quot;@EXX_SIRE_APIS&quot; WHERE &quot;Code&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string HANA_ExisteConfAPI {
            get {
                return ResourceManager.GetString("HANA_ExisteConfAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&quot;Code&quot;, 
        ///	&quot;U_EXX_RUC&quot; || &apos; &apos; ||
        ///	(CASE WHEN &quot;Code&quot; = &apos;0&apos; THEN (SELECT &quot;CompnyName&quot; FROM OADM)
        ///		  ELSE (SELECT &quot;BPLName&quot; FROM OBPL A WHERE A.&quot;BPLId&quot; = T0.&quot;Code&quot;) END)AS &quot;Empresa&quot; 
        ///FROM &quot;@EXX_SIRE_APIS&quot; T0 
        ///ORDER BY TO_INTEGER(T0.&quot;Code&quot;).
        /// </summary>
        internal static string HANA_ListarEmpresas {
            get {
                return ResourceManager.GetString("HANA_ListarEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    &quot;Code&quot;,
        ///    &quot;Name&quot;,
        ///    IFNULL(&quot;U_EXX_ADDN&quot;, &apos;&apos;)   AS &quot;U_EXX_ADDN&quot;,
        ///    IFNULL(&quot;U_EXX_VERS&quot;, &apos;&apos;)   AS &quot;U_EXX_VERS&quot;,
        ///    IFNULL(&quot;U_EXX_RUTA&quot;, &apos;&apos;)   AS &quot;U_EXX_RUTA&quot;
        ///FROM &quot;@EXX_SETUP&quot;;.
        /// </summary>
        internal static string HANA_ListarSetup {
            get {
                return ResourceManager.GetString("HANA_ListarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(*) FROM &quot;OBPL&quot;.
        /// </summary>
        internal static string HANA_MultiBranch {
            get {
                return ResourceManager.GetString("HANA_MultiBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    &quot;Code&quot;,
        ///    IFNULL(&quot;U_EXX_CONS&quot;, &apos;&apos;)   AS &quot;U_EXX_CONS&quot;,
        ///    IFNULL(&quot;U_EXX_URSL&quot;, &apos;&apos;)   AS &quot;U_EXX_URSL&quot;,
        ///    IFNULL(&quot;U_EXX_VSAP&quot;, &apos;&apos;)   AS &quot;U_EXX_VSAP&quot;,
        ///    IFNULL(&quot;U_EXX_VSIR&quot;, &apos;&apos;)   AS &quot;U_EXX_VSIR&quot;
        ///FROM &quot;@EXX_SIRE_CONF&quot;
        ///WHERE &quot;Code&quot; = &apos;01&apos;;.
        /// </summary>
        internal static string HANA_ObtenerConfiguracion {
            get {
                return ResourceManager.GetString("HANA_ObtenerConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&apos;0&apos; AS &quot;BPLId&quot;,
        ///	T0.&quot;TaxIdNum&quot; AS &quot;GlblLocNum&quot;,
        ///	T0.&quot;CompnyName&quot; AS &quot;BPLName&quot;,
        ///	IFNULL(T1.&quot;U_EXX_APIS&quot;, &apos;&apos;) AS &quot;U_EXX_APIS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_USER&quot;, &apos;&apos;) AS &quot;U_EXX_USER&quot;,
        ///	IFNULL(T1.&quot;U_EXX_PASS&quot;, &apos;&apos;) AS &quot;U_EXX_PASS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLID&quot;, &apos;&apos;) AS &quot;U_EXX_CLID&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLSE&quot;, &apos;&apos;) AS &quot;U_EXX_CLSE&quot;
        ///FROM OADM T0
        ///LEFT JOIN &quot;@EXX_SIRE_APIS&quot; T1 ON T1.&quot;Code&quot; = &apos;0&apos;
        ///ORDER BY 1.
        /// </summary>
        internal static string HANA_ObtieneConfAPIxOADM {
            get {
                return ResourceManager.GetString("HANA_ObtieneConfAPIxOADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	T0.&quot;BPLId&quot;,
        ///	T0.&quot;GlblLocNum&quot;,
        ///	T0.&quot;BPLName&quot;,
        ///	IFNULL(T1.&quot;U_EXX_APIS&quot;, &apos;&apos;) AS &quot;U_EXX_APIS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_USER&quot;, &apos;&apos;) AS &quot;U_EXX_USER&quot;,
        ///	IFNULL(T1.&quot;U_EXX_PASS&quot;, &apos;&apos;) AS &quot;U_EXX_PASS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLID&quot;, &apos;&apos;) AS &quot;U_EXX_CLID&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLSE&quot;, &apos;&apos;) AS &quot;U_EXX_CLSE&quot;
        ///FROM OBPL T0
        ///LEFT JOIN &quot;@EXX_SIRE_APIS&quot; T1 ON T0.&quot;BPLId&quot; = T1.&quot;Code&quot;
        ///ORDER BY 1.
        /// </summary>
        internal static string HANA_ObtieneConfAPIxSucursal {
            get {
                return ResourceManager.GetString("HANA_ObtieneConfAPIxSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM OPCH T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0}
        ///AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos;
        ///AND T0.&quot;Indicator&quot; = &apos;{2}&apos;
        ///AND LOCATE(T0.&quot;NumAtCard&quot;, &apos;-&apos;) &gt; 0
        ///AND SUBSTRING(T0.&quot;NumAtCard&quot;, 1, LOCATE(T0.&quot;NumAtCard&quot;, &apos;-&apos;) - 1) = &apos;{3}&apos;
        ///AND LTRIM(SUBSTRING(T0.&quot;NumAtCard&quot;, LOCATE(T0.&quot;NumAtCard&quot;, &apos;-&apos;) + 1),&apos;0&apos;) = LTRIM(&apos;{4}&apos;,&apos;0&apos;)
        ///
        ///UNION ALL
        ///
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM ODPO T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;Card [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HANA_ObtieneLlavesDocumentosCompra {
            get {
                return ResourceManager.GetString("HANA_ObtieneLlavesDocumentosCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT top 10 T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM OINV T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///INNER JOIN NNM1 T2 ON T0.&quot;Series&quot; = T2.&quot;Series&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0}
        ///AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos;
        ///AND T0.&quot;Indicator&quot; = &apos;{2}&apos;
        ///AND (T0.&quot;FolioPref&quot; = &apos;{3}&apos; OR T2.&quot;SeriesName&quot; = &apos;{3}&apos;)
        ///AND T0.&quot;FolioNum&quot; = LTRIM(&apos;{4}&apos;,&apos;0&apos;)
        ///
        ///UNION ALL
        ///
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM ODPI T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///INNER JOIN NNM1 T2 ON T0.&quot;Series&quot; = T2.&quot;Series&quot;        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HANA_ObtieneLlavesDocumentosVenta {
            get {
                return ResourceManager.GetString("HANA_ObtieneLlavesDocumentosVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE &quot;SBO_EXX_SIRE_ASISTENTE_MASIVO&quot; (
        ///	IN TIPO VARCHAR (1) 
        ///	, IN PROCESO VARCHAR (1)
        ///	, IN PERIODO VARCHAR (1) 
        ///) 
        ///AS
        ///BEGIN
        ///
        ///	IF :TIPO = &apos;C&apos; THEN
        ///		IF :PROCESO = &apos;-&apos; THEN
        ///			SELECT 
        ///			(CASE WHEN IFNULL(T2.&quot;DocEntry&quot;, 0) = 0 THEN &apos;N&apos; ELSE &apos;Y&apos; END) AS &quot;Sel&quot;,
        ///			T0.&quot;Code&quot; AS &quot;BPLId&quot;,
        ///			T1.&quot;GlblLocNum&quot;,
        ///			T1.&quot;BPLName&quot; AS &quot;BPLName&quot;,
        ///			T0.&quot;U_EXX_APIS&quot;,
        ///			T0.&quot;U_EXX_USER&quot;,
        ///			T0.&quot;U_EXX_PASS&quot;,
        ///			T0.&quot;U_EXX_CLID&quot;,
        ///			T0.&quot;U_EXX_CLSE&quot;,
        ///			IFNULL(T2.&quot;DocEntry&quot;, 0) &quot;DocEntry&quot;
        ///			FR [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HANA_SBO_EXX_SIRE_ASISTENTE_MASIVO {
            get {
                return ResourceManager.GetString("HANA_SBO_EXX_SIRE_ASISTENTE_MASIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM &quot;@EXX_SIRE_COMP&quot; WHERE &quot;U_EXX_PERIODO&quot; = &apos;{0}&apos; AND &quot;U_EXX_BPLID&quot; = &apos;{1}&apos; AND IFNULL(&quot;Canceled&quot;, &apos;&apos;) = &apos;N&apos;.
        /// </summary>
        internal static string HANA_ValidaExisteRegistroCompra {
            get {
                return ResourceManager.GetString("HANA_ValidaExisteRegistroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM &quot;@EXX_SIRE_VENT&quot; WHERE &quot;U_EXX_PERIODO&quot; = &apos;{0}&apos; AND &quot;U_EXX_BPLID&quot; = &apos;{1}&apos; AND IFNULL(&quot;Canceled&quot;, &apos;&apos;) = &apos;N&apos;.
        /// </summary>
        internal static string HANA_ValidaExisteRegistroVenta {
            get {
                return ResourceManager.GetString("HANA_ValidaExisteRegistroVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TABLE_NAME
        ///FROM SYS.M_TABLES
        ///WHERE SCHEMA_NAME = &apos;{0}&apos;
        ///AND TABLE_NAME = &apos;{1}&apos;;.
        /// </summary>
        internal static string HANA_ValidarTabla {
            get {
                return ResourceManager.GetString("HANA_ValidarTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP 1 Code, U_EXX_DATE, U_EXX_HORA, U_EXX_ARCHTXT, U_EXX_CONTENIDO FROM [@EXX_SIRE_SERV]
        ///WHERE U_EXX_TIPO = {0} AND U_EXX_BPLID = &apos;{1}&apos; AND U_EXX_PERIODO = &apos;{2}&apos; AND U_EXX_ESTADO =0 ORDER BY Code DESC.
        /// </summary>
        internal static string SQL_ConsultaExisteLog {
            get {
                return ResourceManager.GetString("SQL_ConsultaExisteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM [@EXX_SIRE_APIS] WHERE Code = &apos;{0}&apos;.
        /// </summary>
        internal static string SQL_ExisteConfAPI {
            get {
                return ResourceManager.GetString("SQL_ExisteConfAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	Code, 
        ///	U_EXX_RUC + &apos; &apos; +
        ///	(CASE WHEN Code = &apos;0&apos; THEN (SELECT CompnyName FROM OADM)
        ///		  ELSE (SELECT BPLName FROM OBPL A WHERE A.&quot;BPLId&quot; = T0.&quot;Code&quot;) END)AS Empresa 
        ///FROM [@EXX_SIRE_APIS] T0 
        ///ORDER BY CAST(T0.Code AS INT).
        /// </summary>
        internal static string SQL_ListarEmpresas {
            get {
                return ResourceManager.GetString("SQL_ListarEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    Code,
        ///    Name,
        ///    ISNULL(U_EXX_ADDN, &apos;&apos;)    AS U_EXX_ADDN,
        ///    ISNULL(U_EXX_VERS, &apos;&apos;)    AS U_EXX_VERS,
        ///    ISNULL(U_EXX_RUTA, &apos;&apos;)    AS U_EXX_RUTA
        ///FROM [@EXX_SETUP].
        /// </summary>
        internal static string SQL_ListarSetup {
            get {
                return ResourceManager.GetString("SQL_ListarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(*) FROM [OBPL].
        /// </summary>
        internal static string SQL_MultiBranch {
            get {
                return ResourceManager.GetString("SQL_MultiBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    Code,
        ///    ISNULL(U_EXX_CONS, &apos;&apos;)    AS U_EXX_CONS,
        ///    ISNULL(U_EXX_URSL, &apos;&apos;)    AS U_EXX_URSL,
        ///    ISNULL(U_EXX_VSAP, &apos;&apos;)    AS U_EXX_VSAP,
        ///    ISNULL(U_EXX_VSIR, &apos;&apos;)    AS U_EXX_VSIR
        ///FROM [@EXX_SIRE_CONF]
        ///WHERE Code = &apos;01&apos;.
        /// </summary>
        internal static string SQL_ObtenerConfiguracion {
            get {
                return ResourceManager.GetString("SQL_ObtenerConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&apos;0&apos; AS BPLId,
        ///	T0.TaxIdNum AS GlblLocNum,
        ///	T0.CompnyName AS BPLName,
        ///	ISNULL(T1.U_EXX_APIS, &apos;&apos;) AS U_EXX_APIS,
        ///	ISNULL(T1.U_EXX_USER, &apos;&apos;) AS U_EXX_USER,
        ///	ISNULL(T1.U_EXX_PASS, &apos;&apos;) AS U_EXX_PASS,
        ///	ISNULL(T1.U_EXX_CLID, &apos;&apos;) AS U_EXX_CLID,
        ///	ISNULL(T1.U_EXX_CLSE, &apos;&apos;) AS U_EXX_CLSE
        ///FROM [OADM] T0
        ///LEFT JOIN [@EXX_SIRE_APIS] T1 ON T1.Code = &apos;0&apos;
        ///ORDER BY 1.
        /// </summary>
        internal static string SQL_ObtieneConfAPIxOADM {
            get {
                return ResourceManager.GetString("SQL_ObtieneConfAPIxOADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	T0.BPLId,
        ///	T0.GlblLocNum,
        ///	T0.BPLName,
        ///	ISNULL(T1.U_EXX_APIS, &apos;&apos;) AS U_EXX_APIS,
        ///	ISNULL(T1.U_EXX_USER, &apos;&apos;) AS U_EXX_USER,
        ///	ISNULL(T1.U_EXX_PASS, &apos;&apos;) AS U_EXX_PASS,
        ///	ISNULL(T1.U_EXX_CLID, &apos;&apos;) AS U_EXX_CLID,
        ///	ISNULL(T1.U_EXX_CLSE, &apos;&apos;) AS U_EXX_CLSE
        ///FROM [OBPL] T0
        ///LEFT JOIN [@EXX_SIRE_APIS] T1 ON T0.BPLId = T1.Code
        ///ORDER BY 1.
        /// </summary>
        internal static string SQL_ObtieneConfAPIxSucursal {
            get {
                return ResourceManager.GetString("SQL_ObtieneConfAPIxSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM OPCH T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE ISNULL(T0.&quot;BPLId&quot;, 0) = {0}
        ///AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos;
        ///AND T0.&quot;Indicator&quot; = &apos;{2}&apos;
        ///AND CHARINDEX(&apos;-&apos;, T0.&quot;NumAtCard&quot;) &gt; 0
        ///AND LEFT(T0.&quot;NumAtCard&quot;, CHARINDEX(&apos;-&apos;, T0.&quot;NumAtCard&quot;) - 1) = &apos;{3}&apos;
        ///AND SUBSTRING(
        ///        SUBSTRING(T0.&quot;NumAtCard&quot;, CHARINDEX(&apos;-&apos;, T0.&quot;NumAtCard&quot;) + 1, LEN(T0.&quot;NumAtCard&quot;)),
        ///        PATINDEX(&apos;%[^0]%&apos;, SUBSTRING(T0.&quot;NumAtCard&quot;, CHARINDEX(&apos;-&apos;, T0.&quot;NumAtCard&quot;) + 1, LEN(T0.&quot;N [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SQL_ObtieneLlavesDocumentosCompra {
            get {
                return ResourceManager.GetString("SQL_ObtieneLlavesDocumentosCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM OINV T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///INNER JOIN NNM1 T2 ON T0.&quot;Series&quot; = T2.&quot;Series&quot;
        ///WHERE ISNULL(T0.&quot;BPLId&quot;, 0) = {0}
        ///AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos;
        ///AND T0.&quot;Indicator&quot; = &apos;{2}&apos;
        ///AND (T0.&quot;FolioPref&quot; = &apos;{3}&apos; OR T2.&quot;SeriesName&quot; = &apos;{3}&apos;)
        ///AND T0.&quot;FolioNum&quot; = LTRIM(&apos;{4}&apos;,&apos;0&apos;)
        ///
        ///
        ///UNION ALL
        ///
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot;
        ///FROM ODPI T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///INNER JOIN NNM1 T2 ON T0.&quot;Series&quot; = T2.&quot;Series&quot;
        ///WHER [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SQL_ObtieneLlavesDocumentosVenta {
            get {
                return ResourceManager.GetString("SQL_ObtieneLlavesDocumentosVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE SBO_EXX_SIRE_ASISTENTE_MASIVO
        ///    @TIPO VARCHAR(1),
        ///    @PROCESO VARCHAR(1),
        ///    @PERIODO VARCHAR(1)
        ///AS
        ///BEGIN
        ///    SET NOCOUNT ON;
        ///
        ///    -- Cuando tipo es C (Compras)
        ///    IF @TIPO = &apos;C&apos;
        ///    BEGIN
        ///        -- Cuando proceso es &apos;-&apos;
        ///        IF @PROCESO = &apos;-&apos;
        ///        BEGIN
        ///            SELECT 
        ///                (CASE WHEN ISNULL(CAST(T2.DocEntry AS VARCHAR(50)), &apos;&apos;) = &apos;&apos; THEN &apos;N&apos; ELSE &apos;Y&apos; END) AS Sel,
        ///                T0.Code AS BPLId,
        ///                T1.GlblLocNum,
        ///                T [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SQL_SBO_EXX_SIRE_ASISTENTE_MASIVO {
            get {
                return ResourceManager.GetString("SQL_SBO_EXX_SIRE_ASISTENTE_MASIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM [@EXX_SIRE_COMP] WHERE U_EXX_PERIODO = &apos;{0}&apos; AND U_EXX_BPLID = &apos;{1}&apos; AND ISNULL(Canceled, &apos;&apos;) = &apos;N&apos;.
        /// </summary>
        internal static string SQL_ValidaExisteRegistroCompra {
            get {
                return ResourceManager.GetString("SQL_ValidaExisteRegistroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM [@EXX_SIRE_VENT] WHERE U_EXX_PERIODO = &apos;{0}&apos; AND U_EXX_BPLID = &apos;{1}&apos; AND ISNULL(Canceled, &apos;&apos;) = &apos;N&apos;.
        /// </summary>
        internal static string SQL_ValidaExisteRegistroVenta {
            get {
                return ResourceManager.GetString("SQL_ValidaExisteRegistroVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT name
        ///FROM {0}.sys.tables
        ///WHERE name = &apos;{1}&apos;.
        /// </summary>
        internal static string SQL_ValidarTabla {
            get {
                return ResourceManager.GetString("SQL_ValidarTabla", resourceCulture);
            }
        }
    }
}
