//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOnConectorSIRE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOnConectorSIRE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM &quot;@EXX_SIRE_APIS&quot; WHERE &quot;Code&quot; = &apos;{0}&apos;.
        /// </summary>
        internal static string HANA_ExisteConfAPI {
            get {
                return ResourceManager.GetString("HANA_ExisteConfAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&quot;Code&quot;, 
        ///	&quot;U_EXX_RUC&quot; || &apos; &apos; ||
        ///	(CASE WHEN &quot;Code&quot; = &apos;0&apos; THEN (SELECT &quot;CompnyName&quot; FROM OADM)
        ///		  ELSE (SELECT &quot;BPLName&quot; FROM OBPL A WHERE A.&quot;BPLId&quot; = T0.&quot;Code&quot;) END)AS &quot;Empresa&quot; 
        ///FROM &quot;@EXX_SIRE_APIS&quot; T0 
        ///ORDER BY TO_INTEGER(T0.&quot;Code&quot;).
        /// </summary>
        internal static string HANA_ListarEmpresas {
            get {
                return ResourceManager.GetString("HANA_ListarEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    &quot;Code&quot;,
        ///    &quot;Name&quot;,
        ///    IFNULL(&quot;U_EXX_ADDN&quot;, &apos;&apos;)   AS &quot;U_EXX_ADDN&quot;,
        ///    IFNULL(&quot;U_EXX_VERS&quot;, &apos;&apos;)   AS &quot;U_EXX_VERS&quot;,
        ///    IFNULL(&quot;U_EXX_RUTA&quot;, &apos;&apos;)   AS &quot;U_EXX_RUTA&quot;
        ///FROM &quot;@EXX_SETUP&quot;;.
        /// </summary>
        internal static string HANA_ListarSetup {
            get {
                return ResourceManager.GetString("HANA_ListarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(*) FROM &quot;OBPL&quot;.
        /// </summary>
        internal static string HANA_MultiBranch {
            get {
                return ResourceManager.GetString("HANA_MultiBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    &quot;Code&quot;,
        ///    IFNULL(&quot;U_EXX_CONS&quot;, &apos;&apos;)   AS &quot;U_EXX_CONS&quot;,
        ///    IFNULL(&quot;U_EXX_URSL&quot;, &apos;&apos;)   AS &quot;U_EXX_URSL&quot;,
        ///    IFNULL(&quot;U_EXX_VSAP&quot;, &apos;&apos;)   AS &quot;U_EXX_VSAP&quot;,
        ///    IFNULL(&quot;U_EXX_VSIR&quot;, &apos;&apos;)   AS &quot;U_EXX_VSIR&quot;
        ///FROM &quot;@EXX_SIRE_CONF&quot;
        ///WHERE &quot;Code&quot; = &apos;01&apos;;.
        /// </summary>
        internal static string HANA_ObtenerConfiguracion {
            get {
                return ResourceManager.GetString("HANA_ObtenerConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&apos;0&apos; AS &quot;BPLId&quot;,
        ///	T0.&quot;TaxIdNum&quot; AS &quot;GlblLocNum&quot;,
        ///	T0.&quot;CompnyName&quot; AS &quot;BPLName&quot;,
        ///	IFNULL(T1.&quot;U_EXX_APIS&quot;, &apos;&apos;) AS &quot;U_EXX_APIS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_USER&quot;, &apos;&apos;) AS &quot;U_EXX_USER&quot;,
        ///	IFNULL(T1.&quot;U_EXX_PASS&quot;, &apos;&apos;) AS &quot;U_EXX_PASS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLID&quot;, &apos;&apos;) AS &quot;U_EXX_CLID&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLSE&quot;, &apos;&apos;) AS &quot;U_EXX_CLSE&quot;
        ///FROM OADM T0
        ///LEFT JOIN &quot;@EXX_SIRE_APIS&quot; T1 ON T1.&quot;Code&quot; = &apos;0&apos;
        ///ORDER BY 1.
        /// </summary>
        internal static string HANA_ObtieneConfAPIxOADM {
            get {
                return ResourceManager.GetString("HANA_ObtieneConfAPIxOADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	T0.&quot;BPLId&quot;,
        ///	T0.&quot;GlblLocNum&quot;,
        ///	T0.&quot;BPLName&quot;,
        ///	IFNULL(T1.&quot;U_EXX_APIS&quot;, &apos;&apos;) AS &quot;U_EXX_APIS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_USER&quot;, &apos;&apos;) AS &quot;U_EXX_USER&quot;,
        ///	IFNULL(T1.&quot;U_EXX_PASS&quot;, &apos;&apos;) AS &quot;U_EXX_PASS&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLID&quot;, &apos;&apos;) AS &quot;U_EXX_CLID&quot;,
        ///	IFNULL(T1.&quot;U_EXX_CLSE&quot;, &apos;&apos;) AS &quot;U_EXX_CLSE&quot;
        ///FROM OBPL T0
        ///LEFT JOIN &quot;@EXX_SIRE_APIS&quot; T1 ON T0.&quot;BPLId&quot; = T1.&quot;Code&quot;
        ///ORDER BY 1.
        /// </summary>
        internal static string HANA_ObtieneConfAPIxSucursal {
            get {
                return ResourceManager.GetString("HANA_ObtieneConfAPIxSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///FROM OPCH T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0} AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos; AND T0.&quot;Indicator&quot; = &apos;{2}&apos; AND T0.&quot;NumAtCard&quot; = &apos;{3}-{4}&apos; 
        ///UNION ALL
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///FROM ODPO T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0} AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos; AND T0.&quot;Indicator&quot; = &apos;{2}&apos; AND T0.&quot;NumAtCard&quot; = &apos;{3}-{4}&apos; 
        ///UNION ALL
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HANA_ObtieneLlavesDocumentos {
            get {
                return ResourceManager.GetString("HANA_ObtieneLlavesDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM &quot;@EXX_SIRE_COMP&quot; WHERE &quot;U_EXX_PERIODO&quot; = &apos;{0}&apos; AND &quot;U_EXX_BPLID&quot; = &apos;{1}&apos;.
        /// </summary>
        internal static string HANA_ValidaExisteRegistroCompra {
            get {
                return ResourceManager.GetString("HANA_ValidaExisteRegistroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TABLE_NAME
        ///FROM SYS.M_TABLES
        ///WHERE SCHEMA_NAME = &apos;{0}&apos;
        ///AND TABLE_NAME = &apos;{1}&apos;;.
        /// </summary>
        internal static string HANA_ValidarTabla {
            get {
                return ResourceManager.GetString("HANA_ValidarTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM [@EXX_SIRE_APIS] WHERE Code = &apos;{0}&apos;.
        /// </summary>
        internal static string SQL_ExisteConfAPI {
            get {
                return ResourceManager.GetString("SQL_ExisteConfAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	Code, 
        ///	U_EXX_RUC + &apos; &apos; +
        ///	(CASE WHEN Code = &apos;0&apos; THEN (SELECT CompnyName FROM OADM)
        ///		  ELSE (SELECT BPLName FROM OBPL A WHERE A.&quot;BPLId&quot; = T0.&quot;Code&quot;) END)AS Empresa 
        ///FROM [@EXX_SIRE_APIS] T0 
        ///ORDER BY CAST(T0.Code AS INT).
        /// </summary>
        internal static string SQL_ListarEmpresas {
            get {
                return ResourceManager.GetString("SQL_ListarEmpresas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    Code,
        ///    Name
        ///    ISNULL(U_EXX_ADDN, &apos;&apos;)    AS U_EXX_ADDN,
        ///    ISNULL(U_EXX_VERS, &apos;&apos;)    AS U_EXX_VERS,
        ///    ISNULL(U_EXX_RUTA, &apos;&apos;)    AS U_EXX_RUTA
        ///FROM [@EXX_SETUP];.
        /// </summary>
        internal static string SQL_ListarSetup {
            get {
                return ResourceManager.GetString("SQL_ListarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT COUNT(*) FROM [OBPL].
        /// </summary>
        internal static string SQL_MultiBranch {
            get {
                return ResourceManager.GetString("SQL_MultiBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    Code,
        ///    ISNULL(U_EXX_CONS, &apos;&apos;)    AS U_EXX_CONS,
        ///    ISNULL(U_EXX_URSL, &apos;&apos;)    AS U_EXX_URSL,
        ///    ISNULL(U_EXX_VSAP, &apos;&apos;)    AS U_EXX_VSAP,
        ///    ISNULL(U_EXX_VSIR, &apos;&apos;)    AS U_EXX_VSIR
        ///FROM [@EXX_SIRE_CONF]
        ///WHERE Code, = &apos;01&apos;;.
        /// </summary>
        internal static string SQL_ObtenerConfiguracion {
            get {
                return ResourceManager.GetString("SQL_ObtenerConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	&apos;0&apos; AS BPLId,
        ///	T0.TaxIdNum AS GlblLocNum,
        ///	T0.CompnyName AS BPLName,
        ///	ISNULL(T1.U_EXX_APIS, &apos;&apos;) AS U_EXX_APIS,
        ///	ISNULL(T1.U_EXX_USER, &apos;&apos;) AS U_EXX_USER,
        ///	ISNULL(T1.U_EXX_PASS, &apos;&apos;) AS U_EXX_PASS,
        ///	ISNULL(T1.U_EXX_CLID, &apos;&apos;) AS U_EXX_CLID,
        ///	ISNULL(T1.U_EXX_CLSE, &apos;&apos;) AS U_EXX_CLSE
        ///FROM [OADM] T0
        ///LEFT JOIN [@EXX_SIRE_APIS] T1 ON T1.Code = &apos;0&apos;
        ///ORDER BY 1.
        /// </summary>
        internal static string SQL_ObtieneConfAPIxOADM {
            get {
                return ResourceManager.GetString("SQL_ObtieneConfAPIxOADM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///	T0.BPLId,
        ///	T0.GlblLocNum,
        ///	T0.BPLName,
        ///	ISNULL(T1.U_EXX_APIS, &apos;&apos;) AS U_EXX_APIS,
        ///	ISNULL(T1.U_EXX_USER, &apos;&apos;) AS U_EXX_USER,
        ///	ISNULL(T1.U_EXX_PASS, &apos;&apos;) AS U_EXX_PASS,
        ///	ISNULL(T1.U_EXX_CLID, &apos;&apos;) AS U_EXX_CLID,
        ///	ISNULL(T1.U_EXX_CLSE, &apos;&apos;) AS U_EXX_CLSE
        ///FROM [OBPL] T0
        ///LEFT JOIN [@EXX_SIRE_APIS] T1 ON T0.BPLId = T1.Code
        ///ORDER BY 1.
        /// </summary>
        internal static string SQL_ObtieneConfAPIxSucursal {
            get {
                return ResourceManager.GetString("SQL_ObtieneConfAPIxSucursal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///FROM OPCH T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0} AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos; AND T0.&quot;Indicator&quot; = &apos;{2}&apos; AND T0.&quot;NumAtCard&quot; = &apos;{3}-{4}&apos; 
        ///UNION ALL
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///FROM ODPO T0
        ///INNER JOIN OCRD T1 ON T0.&quot;CardCode&quot; = T1.&quot;CardCode&quot;
        ///WHERE IFNULL(T0.&quot;BPLId&quot;, 0) = {0} AND T1.&quot;LicTradNum&quot; = &apos;{1}&apos; AND T0.&quot;Indicator&quot; = &apos;{2}&apos; AND T0.&quot;NumAtCard&quot; = &apos;{3}-{4}&apos; 
        ///UNION ALL
        ///SELECT T0.&quot;ObjType&quot;, T0.&quot;DocEntry&quot; 
        ///F [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string SQL_ObtieneLlavesDocumentos {
            get {
                return ResourceManager.GetString("SQL_ObtieneLlavesDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT * FROM [@EXX_SIRE_COMP] WHERE U_EXX_PERIODO = &apos;{0}&apos; AND U_EXX_BPLID = &apos;{1}&apos;.
        /// </summary>
        internal static string SQL_ValidaExisteRegistroCompra {
            get {
                return ResourceManager.GetString("SQL_ValidaExisteRegistroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TABLE_NAME
        ///FROM SYS.M_TABLES
        ///WHERE SCHEMA_NAME = &apos;{0}&apos;
        ///AND TABLE_NAME = &apos;{1}&apos;;.
        /// </summary>
        internal static string SQL_ValidarTabla {
            get {
                return ResourceManager.GetString("SQL_ValidarTabla", resourceCulture);
            }
        }
    }
}
